apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: it-tools
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: it-tools
  patches:
    - target:
        kind: Ingress
        name: it-tools
      patch: |
        - op: add
          path: /metadata/annotations/external-dns.alpha.kubernetes.io~1target
          value: "192.168.1.100"  # Replace with your ingress controller IP
