apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- networking/cert-manager.yaml
- networking/cert-manager-issuers.yaml
- networking/external-dns.yaml

- networking/ingress-nginx.yaml
- networking/ingress-nginx-namespace.yaml
- networking/etcd.yaml

- networking/metallb-namespace.yaml
- networking/metallb.yaml
- networking/metallb-config.yaml
- networking/coredns-configmap.yaml
- networking/coredns-service.yaml
- flux-system/gotk-components.yaml
- flux-system/gotk-sync.yaml
- storage/local-path-provisioner.yaml


- apps/it-tools.yaml
- apps/glance.yaml
- apps/nextcloud.yaml
- apps/postgres.yaml

configMapGenerator:
  - name: glance-config
    namespace: glance
    files:
      - glance.yml=apps/glance-config.yml


