theme:
  light: false
pages:
  - name: Home
    columns:
      - size: small
        widgets:
          - type: clock
            hour-format: 24h
          - type: weather
            location: Nairobi, Kenya
      - size: full
        widgets:
          - type: videos
            title: YouTube
            style: horizontal-cards
            limit: 4
            channels:
              - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
              - UCBJycsmduvYEL83R_U4JriQ # Marques Brownlee
          - type: rss
            title: Blogs
            style: horizontal-cards
            limit: 4
            feeds:
              - url: https://kubernetes.io/feed.xml
                title: Kubernetes Blog
              - url: https://www.jeffgeerling.com/blog.xml
                title: Jeff Geerling
  - name: Homelab
    columns:
      - size: small
        widgets:
          - type: clock
            hour-format: 24h
          - type: weather
            location: Nairobi, Kenya
      - size: full
        widgets:
          - type: monitor
            title: Status
            sites:
              - title: IT Tools
                url: https://tools.eduuh.home
                allow-insecure: true
              - title: Nextcloud
                url: https://nextcloud.eduuh.home
                allow-insecure: true
              - title: Glance
                url: https://glance.eduuh.home
                icon: si:glance
                allow-insecure: true
              - title: n8n
                url: https://n8n.eduuh.home
                icon: si:n8n
                allow-insecure: true
              - title: Grafana
                url: https://grafana.eduuh.home
                icon: si:grafana
                allow-insecure: true
